import { slugify } from "./slug";

export type Category =
  | "Actions"
  | "Forms"
  | "Navigation"
  | "Overlays"
  | "Data Display"
  | "Feedback"
  | "Layout"
  | "Media"
  | "Marketing"
  | "AI"
  | "Animation"
  | "Auth"
  | "Dashboard";

export type ComponentEntry = {
  name: string;
  slug: string;
  category: Category;
  kind: string; // renderer key
  variant?: string; // variant key passed to renderer
  description: string;
  tags: string[];
  props?: { name: string; type: string; default?: string; description: string }[];
  a11y?: string[];
  code?: string;
  usage?: string;
  cli?: string;
  pkg?: string;
  isNew?: boolean;
};

const defaultProps = [
  { name: "className", type: "string", description: "Tailwind classes appended to the root." },
  { name: "children", type: "ReactNode", description: "Slot content." },
];

const defaultA11y = [
  "Keyboard focus visible (focus-visible ring).",
  "Color contrast meets WCAG AA on canvas and dark surfaces.",
  "Semantic landmark / ARIA role applied where relevant.",
];

const make = (
  name: string,
  category: Category,
  kind: string,
  description: string,
  extras: Partial<ComponentEntry> = {},
): ComponentEntry => ({
  name,
  slug: slugify(name),
  category,
  kind,
  description,
  tags: [category.toLowerCase(), kind, ...(extras.tags ?? [])],
  props: extras.props ?? defaultProps,
  a11y: extras.a11y ?? defaultA11y,
  cli: extras.cli ?? `npx vanta-ui add ${slugify(name)}`,
  pkg: extras.pkg ?? `npm i @vanta-ui/${slugify(name)}`,
  usage:
    extras.usage ??
    `import { ${name.replace(/\s+/g, "")} } from "@vanta-ui/react";\n\nexport default function Example() {\n  return <${name.replace(/\s+/g, "")} />;\n}`,
  code:
    extras.code ??
    `// ${name} — Vanta UI\nexport function ${name.replace(/\s+/g, "")}(props) {\n  return (\n    /* see live preview */\n    null\n  );\n}`,
  ...extras,
});

// Programmatic catalog. Each entry maps to a renderer in preview-renderers.tsx
// via { kind, variant }.
export const COMPONENTS: ComponentEntry[] = [
  // Actions — Buttons (15)
  make("Button", "Actions", "button", "Primary pill button in ink primary."),
  make("Button Secondary", "Actions", "button", "Outline pill button on canvas.", { variant: "secondary" }),
  make("Button Ghost", "Actions", "button", "Ghost button with hover canvas-soft.", { variant: "ghost" }),
  make("Button Link", "Actions", "button", "Inline link-styled button.", { variant: "link" }),
  make("Button Gradient", "Actions", "button", "Mesh-gradient hero CTA.", { variant: "gradient" }),
  make("Button Destructive", "Actions", "button", "Critical action button.", { variant: "destructive" }),
  make("Button Loading", "Actions", "button", "Async pending state.", { variant: "loading" }),
  make("Button Sizes", "Actions", "button", "sm, md, lg, xl scales.", { variant: "sizes" }),
  make("Icon Button", "Actions", "icon-button", "Square icon-only button."),
  make("Toggle Button", "Actions", "toggle", "On/off toggle button."),
  make("Button Group", "Actions", "button-group", "Segmented button group."),
  make("Split Button", "Actions", "split-button", "Button with dropdown affordance."),
  make("Floating Action Button", "Actions", "fab", "Fixed circular action."),
  make("Copy Button", "Actions", "copy-button", "Click-to-copy with state."),
  make("Link", "Actions", "link", "Inline link with hover underline."),

  // Badges & Tags (10)
  make("Badge", "Data Display", "badge", "Soft secondary badge."),
  make("Badge Solid", "Data Display", "badge", "Solid ink badge.", { variant: "solid" }),
  make("Badge Outline", "Data Display", "badge", "Outline badge.", { variant: "outline" }),
  make("Status Badge", "Data Display", "badge", "Status dot + label.", { variant: "status" }),
  make("Gradient Badge", "Data Display", "badge", "Mesh-gradient text badge.", { variant: "gradient" }),
  make("Chip", "Data Display", "chip", "Dismissable chip."),
  make("Tag", "Data Display", "tag", "Mono caption tag."),
  make("Counter Badge", "Data Display", "badge", "Numeric counter pill.", { variant: "counter" }),
  make("Kbd", "Data Display", "kbd", "Keyboard key cap."),
  make("Pill", "Data Display", "badge", "Pill announcement.", { variant: "pill" }),

  // Avatars (6)
  make("Avatar", "Data Display", "avatar", "User avatar with fallback."),
  make("Avatar Sizes", "Data Display", "avatar", "xs → 2xl scale.", { variant: "sizes" }),
  make("Avatar Group", "Data Display", "avatar", "Stacked avatars with overflow.", { variant: "group" }),
  make("Avatar Status", "Data Display", "avatar", "Avatar with presence dot.", { variant: "status" }),
  make("Avatar Square", "Data Display", "avatar", "Squircle avatar.", { variant: "square" }),
  make("Initials Avatar", "Data Display", "avatar", "Generated initials.", { variant: "initials" }),

  // Overlays (12)
  make("Tooltip", "Overlays", "tooltip", "Hover tooltip with arrow."),
  make("Popover", "Overlays", "popover", "Anchored popover panel."),
  make("Dropdown", "Overlays", "dropdown", "Dropdown menu with items."),
  make("Context Menu", "Overlays", "context-menu", "Right-click context menu."),
  make("Menu Bar", "Overlays", "menu-bar", "Top menu bar."),
  make("Command Menu", "Overlays", "command-menu", "Cmd+K command palette."),
  make("Modal", "Overlays", "modal", "Centered modal."),
  make("Dialog", "Overlays", "modal", "Form dialog.", { variant: "dialog" }),
  make("Alert Dialog", "Overlays", "modal", "Destructive confirm dialog.", { variant: "alert" }),
  make("Drawer", "Overlays", "drawer", "Side drawer."),
  make("Sheet", "Overlays", "drawer", "Bottom sheet.", { variant: "bottom" }),
  make("Hover Card", "Overlays", "hover-card", "User hover preview card."),

  // Navigation (14)
  make("Navbar", "Navigation", "navbar", "Top navigation bar."),
  make("Navbar Centered", "Navigation", "navbar", "Centered logo navbar.", { variant: "centered" }),
  make("Sidebar", "Navigation", "sidebar", "App sidebar."),
  make("Tabs", "Navigation", "tabs", "Underline tabs."),
  make("Tabs Pill", "Navigation", "tabs", "Pill tabs.", { variant: "pill" }),
  make("Vertical Tabs", "Navigation", "tabs", "Vertical tabs.", { variant: "vertical" }),
  make("Accordion", "Navigation", "accordion", "Stacked accordion."),
  make("Collapse", "Navigation", "collapse", "Single collapse."),
  make("Breadcrumb", "Navigation", "breadcrumb", "Path breadcrumb."),
  make("Pagination", "Navigation", "pagination", "Numbered pagination."),
  make("Stepper", "Navigation", "stepper", "Multi-step progress."),
  make("Dock", "Navigation", "dock", "macOS-style dock."),
  make("Floating Menu", "Navigation", "floating-menu", "Floating action menu."),
  make("User Menu", "Navigation", "user-menu", "Avatar dropdown menu."),

  // Cards (10)
  make("Card", "Layout", "card", "Hairline card on canvas."),
  make("Glass Card", "Layout", "card", "Frosted glass card over mesh.", { variant: "glass" }),
  make("Profile Card", "Layout", "card", "User profile card.", { variant: "profile" }),
  make("Product Card", "Layout", "card", "E-commerce product.", { variant: "product" }),
  make("Stat Card", "Layout", "card", "KPI stat card.", { variant: "stat" }),
  make("Pricing Card", "Layout", "card", "Pricing tier card.", { variant: "pricing" }),
  make("Pricing Featured", "Layout", "card", "Featured ink tier.", { variant: "pricing-featured" }),
  make("Feature Card", "Layout", "card", "Feature with icon.", { variant: "feature" }),
  make("Template Card", "Layout", "card", "Template thumbnail.", { variant: "template" }),
  make("Spotlight Card", "Layout", "card", "Mouse-follow spotlight.", { variant: "spotlight" }),

  // Feedback (12)
  make("Toast", "Feedback", "toast", "Notification toast."),
  make("Snackbar", "Feedback", "toast", "Action snackbar.", { variant: "snackbar" }),
  make("Alert", "Feedback", "alert", "Inline alert info."),
  make("Alert Success", "Feedback", "alert", "Success alert.", { variant: "success" }),
  make("Alert Warning", "Feedback", "alert", "Warning alert.", { variant: "warning" }),
  make("Alert Error", "Feedback", "alert", "Error alert.", { variant: "error" }),
  make("Banner", "Feedback", "banner", "Top page banner."),
  make("Progress Bar", "Feedback", "progress", "Linear progress."),
  make("Circular Progress", "Feedback", "progress", "Radial progress.", { variant: "circular" }),
  make("Skeleton", "Feedback", "skeleton", "Loading placeholder."),
  make("Loader", "Feedback", "loader", "Dots loader."),
  make("Spinner", "Feedback", "loader", "Ring spinner.", { variant: "ring" }),

  // Forms (20)
  make("Input", "Forms", "input", "Text input."),
  make("Input With Icon", "Forms", "input", "Input with leading icon.", { variant: "icon" }),
  make("Input Sizes", "Forms", "input", "sm/md/lg.", { variant: "sizes" }),
  make("Textarea", "Forms", "textarea", "Multiline input."),
  make("Search Input", "Forms", "input", "Search with kbd hint.", { variant: "search" }),
  make("OTP Input", "Forms", "otp", "One-time-passcode input."),
  make("Pin Input", "Forms", "otp", "Numeric PIN.", { variant: "pin" }),
  make("Checkbox", "Forms", "checkbox", "Checkbox."),
  make("Checkbox Group", "Forms", "checkbox", "Checkbox group.", { variant: "group" }),
  make("Radio Group", "Forms", "radio", "Radio group."),
  make("Switch", "Forms", "switch", "Toggle switch."),
  make("Slider", "Forms", "slider", "Single-value slider."),
  make("Range Slider", "Forms", "slider", "Two-thumb range.", { variant: "range" }),
  make("Select", "Forms", "select", "Native-style select."),
  make("Multi Select", "Forms", "select", "Multiple chips select.", { variant: "multi" }),
  make("Combobox", "Forms", "select", "Searchable select.", { variant: "combobox" }),
  make("Date Picker", "Forms", "date", "Single date picker."),
  make("Time Picker", "Forms", "date", "Time picker.", { variant: "time" }),
  make("Calendar", "Forms", "date", "Inline calendar.", { variant: "calendar" }),
  make("Form", "Forms", "form", "Full sign-in form."),

  // Forms supplemental (6)
  make("Field", "Forms", "field", "Labelled field row."),
  make("Label", "Forms", "field", "Standalone label.", { variant: "label" }),
  make("Password Input", "Forms", "input", "Password with reveal.", { variant: "password" }),
  make("File Upload", "Forms", "upload", "File picker."),
  make("Drag Upload", "Forms", "upload", "Drag-and-drop dropzone.", { variant: "drag" }),
  make("Color Picker", "Forms", "color-picker", "Color picker with swatches."),

  // Data Display (14)
  make("Table", "Data Display", "table", "Hairline table."),
  make("Data Table", "Data Display", "table", "Sortable data table.", { variant: "data" }),
  make("List", "Data Display", "list", "Stacked list."),
  make("Grid", "Data Display", "grid", "Auto-fit grid."),
  make("Tree View", "Data Display", "tree", "Folder tree."),
  make("Timeline", "Data Display", "timeline", "Vertical timeline."),
  make("Activity Feed", "Data Display", "feed", "Activity stream."),
  make("Stat Group", "Data Display", "stats", "Stats row."),
  make("Empty State", "Data Display", "empty", "Empty state with action."),
  make("Divider", "Data Display", "divider", "Hairline divider."),
  make("Separator", "Data Display", "divider", "Labelled separator.", { variant: "label" }),
  make("Kanban Board", "Data Display", "kanban", "Three-column kanban."),
  make("Tree Folder", "Data Display", "tree", "Files tree.", { variant: "files" }),
  make("Description List", "Data Display", "list", "Key-value list.", { variant: "desc" }),

  // Marketing (10)
  make("Hero Section", "Marketing", "hero", "Mesh-gradient hero."),
  make("Hero Split", "Marketing", "hero", "Split image hero.", { variant: "split" }),
  make("Feature Section", "Marketing", "feature-section", "3-up feature grid."),
  make("Pricing Section", "Marketing", "pricing-section", "Pricing tiers."),
  make("FAQ Section", "Marketing", "faq", "Stacked FAQ."),
  make("Testimonial Section", "Marketing", "testimonial", "Testimonials grid."),
  make("CTA Section", "Marketing", "cta", "Polarity-flipped CTA."),
  make("Newsletter Section", "Marketing", "newsletter", "Email signup band."),
  make("Logo Strip", "Marketing", "logo-strip", "Customer logos."),
  make("Stats Band", "Marketing", "stats", "Big-number stats band.", { variant: "band" }),

  // Site chrome
  make("Header", "Layout", "header", "Marketing header."),
  make("Footer", "Layout", "footer", "Marketing footer."),
  make("Dashboard Layout", "Layout", "dashboard-shell", "Sidebar + content shell."),
  make("Split View", "Layout", "split-view", "Resizable split view."),
  make("Resizable Panel", "Layout", "split-view", "Resizable panels.", { variant: "panels" }),
  make("Masonry Grid", "Layout", "masonry", "Pinterest-style grid."),

  // Auth (4)
  make("Login Form", "Auth", "form", "Sign-in form.", { variant: "login" }),
  make("Register Form", "Auth", "form", "Sign-up form.", { variant: "register" }),
  make("Forgot Password", "Auth", "form", "Forgot password form.", { variant: "forgot" }),
  make("Profile Menu", "Auth", "user-menu", "Profile dropdown.", { variant: "profile" }),

  // Dashboard / AI (10)
  make("Analytics Card", "Dashboard", "card", "KPI with sparkline.", { variant: "analytics" }),
  make("Chart", "Dashboard", "chart", "Area chart."),
  make("Bar Chart", "Dashboard", "chart", "Bar chart.", { variant: "bar" }),
  make("Line Chart", "Dashboard", "chart", "Line chart.", { variant: "line" }),
  make("Notification Panel", "Dashboard", "feed", "Notifications panel.", { variant: "notif" }),
  make("Chat Bubble", "AI", "chat", "User + AI bubble."),
  make("Chat Input", "AI", "chat", "Composer.", { variant: "input" }),
  make("AI Chat UI", "AI", "chat", "Full AI chat surface.", { variant: "full" }),
  make("Prompt Box", "AI", "chat", "Prompt textarea.", { variant: "prompt" }),
  make("Command Palette", "AI", "command-menu", "Cmd-K palette.", { variant: "palette" }),

  // Media (12)
  make("Terminal UI", "Media", "terminal", "Terminal mockup."),
  make("Code Block", "Media", "code-block", "Syntax code block."),
  make("Image Gallery", "Media", "gallery", "Image gallery grid."),
  make("Carousel", "Media", "carousel", "Slide carousel."),
  make("Swiper", "Media", "carousel", "Card swiper.", { variant: "cards" }),
  make("Marquee", "Media", "marquee", "Infinite marquee."),
  make("Video Player", "Media", "video", "Video player."),
  make("Audio Player", "Media", "audio", "Audio player."),
  make("Map Embed", "Media", "map", "Map embed."),
  make("Cursor Effect", "Media", "cursor", "Custom cursor."),
  make("Parallax Section", "Media", "parallax", "Parallax scroll."),
  make("Scroll Animation", "Animation", "scroll-reveal", "Scroll reveal."),

  // Animation (10)
  make("Reveal Animation", "Animation", "scroll-reveal", "Fade-up reveal.", { variant: "fade" }),
  make("Hover Card Effect", "Animation", "hover-card", "3D tilt card.", { variant: "tilt" }),
  make("Spotlight Effect", "Animation", "card", "Mouse spotlight.", { variant: "spotlight" }),
  make("Glass Panel", "Animation", "card", "Glass panel.", { variant: "glass" }),
  make("Marquee Logos", "Animation", "marquee", "Logos marquee.", { variant: "logos" }),
  make("Animated Beam", "Animation", "beam", "Connect nodes with beam."),
  make("Aurora Background", "Animation", "aurora", "Aurora animated bg."),
  make("Grid Beam", "Animation", "grid-beam", "Animated grid beam."),
  make("Particles", "Animation", "particles", "Floating particles."),
  make("Number Ticker", "Animation", "ticker", "Animated number."),

  // Theme + utilities (8)
  make("Theme Switcher", "Actions", "theme-switcher", "Light/dark toggle."),
  make("Light Mode", "Actions", "theme-switcher", "Light mode preview.", { variant: "light" }),
  make("Dark Mode", "Actions", "theme-switcher", "Dark mode preview.", { variant: "dark" }),
  make("Color Swatch", "Data Display", "swatch", "Color token swatch."),
  make("Typography Scale", "Data Display", "typescale", "Type scale preview."),
  make("Spacing Scale", "Data Display", "spacing-scale", "Spacing scale."),
  make("Icon Library", "Data Display", "icons", "Lucide icon grid."),
  make("Infinite Scroll", "Animation", "infinite-scroll", "Infinite list."),

  // Misc (10)
  make("Virtual List", "Data Display", "list", "Virtualized list.", { variant: "virtual" }),
  make("Drag and Drop", "Animation", "dnd", "Drag and drop list."),
  make("Tree Select", "Forms", "tree", "Tree select.", { variant: "select" }),
  make("Tag Input", "Forms", "input", "Tag input.", { variant: "tags" }),
  make("Mention Input", "Forms", "input", "@ mention input.", { variant: "mention" }),
  make("Rating", "Forms", "rating", "Star rating."),
  make("Avatar Picker", "Forms", "avatar", "Avatar picker.", { variant: "picker" }),
  make("Theme Customizer", "Actions", "theme-switcher", "Token customizer.", { variant: "customizer" }),
  make("Responsive Preview", "Layout", "responsive-preview", "Device frames."),
  make("Showcase Tile", "Marketing", "card", "Showcase tile.", { variant: "showcase" }),

  // Additional pack (15) to push the catalog past 200
  make("Hero Mesh", "Marketing", "hero", "Hero with mesh background.", { variant: "mesh" }),
  make("Hero Terminal", "Marketing", "hero", "Hero with terminal demo.", { variant: "terminal" }),
  make("Feature Bento", "Marketing", "feature-section", "Bento feature grid.", { variant: "bento" }),
  make("Pricing Compare", "Marketing", "pricing-section", "Compare plans table.", { variant: "compare" }),
  make("Testimonial Marquee", "Marketing", "testimonial", "Scrolling testimonials.", { variant: "marquee" }),
  make("Stat Sparkline", "Dashboard", "card", "Stat with sparkline.", { variant: "stat-spark" }),
  make("Settings Form", "Forms", "form", "Settings form.", { variant: "settings" }),
  make("Search Modal", "Overlays", "command-menu", "Search modal.", { variant: "search" }),
  make("Notification Toast", "Feedback", "toast", "Stacked toasts.", { variant: "stack" }),
  make("Status Page Row", "Data Display", "list", "Status row.", { variant: "status" }),
  make("Logo Mark", "Layout", "logo", "Brand logo mark."),
  make("Avatar Stack Large", "Data Display", "avatar", "Large avatar stack.", { variant: "group-lg" }),
  make("Gradient Heading", "Animation", "ticker", "Gradient gradient heading.", { variant: "gradient-heading" }),
  make("Glow Card", "Animation", "card", "Glow border card.", { variant: "glow" }),
  make("Bento Layout", "Layout", "masonry", "Bento mixed grid.", { variant: "bento" }),
];

// =================================================================
// v2 — +200 PREMIUM COMPONENTS (AI, Dashboard, Marketing, Forms…)
// =================================================================
const v2: ComponentEntry[] = [
  // ---------- AI (40) ----------
  make("AI Profile", "AI", "ai-profile", "Premium AI assistant profile card with avatar, role, and capability chips.", { isNew: true }),
  make("AI Profile Coder", "AI", "ai-profile", "Code companion profile.", { variant: "coder", isNew: true }),
  make("AI Profile Designer", "AI", "ai-profile", "Design partner profile.", { variant: "designer", isNew: true }),
  make("AI Profile Writer", "AI", "ai-profile", "Editorial AI profile.", { variant: "writer", isNew: true }),
  make("AI Profile Analyst", "AI", "ai-profile", "Data analyst AI profile.", { variant: "analyst", isNew: true }),
  make("AI Agent Running", "AI", "ai-agent", "Live agent execution card.", { variant: "running", isNew: true }),
  make("AI Agent Idle", "AI", "ai-agent", "Idle agent card.", { variant: "idle", isNew: true }),
  make("AI Agent Failed", "AI", "ai-agent", "Failed agent card.", { variant: "error", isNew: true }),
  make("AI Agent Queued", "AI", "ai-agent", "Queued agent card.", { variant: "queued", isNew: true }),
  make("AI Persona Switcher", "AI", "ai-persona", "Switch between AI personas.", { isNew: true }),
  make("AI Prompt Card", "AI", "ai-prompt-card", "Prompt template card.", { isNew: true }),
  make("AI Prompt Code", "AI", "ai-prompt-card", "Code prompt template.", { variant: "code", isNew: true }),
  make("AI Prompt SEO", "AI", "ai-prompt-card", "SEO prompt template.", { variant: "seo", isNew: true }),
  make("AI Prompt Image", "AI", "ai-prompt-card", "Image-generation prompt.", { variant: "image", isNew: true }),
  make("AI Tool Call", "AI", "ai-tool-call", "Tool invocation block.", { isNew: true }),
  make("AI Citation Block", "AI", "ai-citation", "Source citation list.", { isNew: true }),
  make("AI Suggestion Chips", "AI", "ai-suggestion", "Suggested follow-up chips.", { isNew: true }),
  make("AI Model Picker", "AI", "ai-model-picker", "Pick the underlying LLM.", { isNew: true }),
  make("AI Streaming", "AI", "ai-stream", "Streaming response with cursor.", { isNew: true }),
  make("AI Memory", "AI", "ai-memory", "Persistent memory items.", { isNew: true }),
  make("AI Token Usage", "AI", "ai-token-usage", "Token + cost meter.", { isNew: true }),
  make("AI Chat Thread", "AI", "chat", "Threaded chat.", { variant: "full", isNew: true }),
  make("AI Prompt Box", "AI", "chat", "Prompt composer.", { variant: "prompt", isNew: true }),
  make("AI Voice Input", "AI", "chat", "Voice prompt input.", { variant: "input", isNew: true }),
  make("AI Code Helper", "AI", "ai-prompt-card", "Inline code helper.", { variant: "code", isNew: true }),
  make("AI Translator", "AI", "ai-prompt-card", "Translation prompt.", { variant: "default", isNew: true }),
  make("AI Vision Card", "AI", "ai-profile", "Vision-enabled persona.", { variant: "default", isNew: true }),
  make("AI Voice Card", "AI", "ai-profile", "Voice-enabled persona.", { variant: "writer", isNew: true }),
  make("AI Agent Marketplace", "AI", "ai-persona", "Browse community agents.", { isNew: true }),
  make("AI Compare", "AI", "ai-model-picker", "Compare two models.", { isNew: true }),
  make("AI Rewriter", "AI", "ai-prompt-card", "Rewrite text in any tone.", { variant: "default", isNew: true }),
  make("AI Summarizer", "AI", "ai-prompt-card", "Summarize any document.", { variant: "default", isNew: true }),
  make("AI Chart Builder", "AI", "ai-prompt-card", "Generate charts from prompts.", { variant: "seo", isNew: true }),
  make("AI Cover Generator", "AI", "ai-prompt-card", "Generate blog covers.", { variant: "image", isNew: true }),
  make("AI Auto-Reply", "AI", "ai-suggestion", "Auto-suggested replies.", { isNew: true }),
  make("AI Knowledge Source", "AI", "ai-citation", "Knowledge sources list.", { isNew: true }),
  make("AI Cost Budget", "AI", "ai-token-usage", "Per-team budget tracker.", { isNew: true }),
  make("AI Workflow", "AI", "ai-agent", "Multi-step workflow.", { variant: "running", isNew: true }),
  make("AI Skill Card", "AI", "ai-prompt-card", "Reusable skill.", { variant: "default", isNew: true }),
  make("AI Avatar Bot", "AI", "ai-profile", "Compact avatar bot.", { variant: "coder", isNew: true }),

  // ---------- Dashboard / Data (35) ----------
  make("KPI Tile Blue", "Dashboard", "kpi-tile", "Bold blue KPI tile.", { variant: "blue", isNew: true }),
  make("KPI Tile Violet", "Dashboard", "kpi-tile", "Violet KPI tile.", { variant: "violet", isNew: true }),
  make("KPI Tile Pink", "Dashboard", "kpi-tile", "Pink KPI tile.", { variant: "pink", isNew: true }),
  make("KPI Tile Cyan", "Dashboard", "kpi-tile", "Cyan KPI tile.", { variant: "cyan", isNew: true }),
  make("KPI Tile Amber", "Dashboard", "kpi-tile", "Amber KPI tile.", { variant: "amber", isNew: true }),
  make("KPI Tile Green", "Dashboard", "kpi-tile", "Green KPI tile.", { variant: "green", isNew: true }),
  make("Gauge Meter", "Dashboard", "gauge", "Radial percentage gauge.", { isNew: true }),
  make("Metric Row", "Dashboard", "metric-row", "4-up metric row with deltas.", { isNew: true }),
  make("Calendar Heatmap", "Dashboard", "calendar-heat", "GitHub-style activity heatmap.", { isNew: true }),
  make("Feature Flags", "Dashboard", "feature-flag", "Feature flag toggles.", { isNew: true }),
  make("DB Query Card", "Dashboard", "db-query", "Live SQL query card.", { isNew: true }),
  make("Log Viewer", "Dashboard", "log-viewer", "Realtime log stream.", { isNew: true }),
  make("JSON Viewer", "Dashboard", "json-viewer", "Pretty JSON output.", { isNew: true }),
  make("Code Diff", "Dashboard", "code-diff", "Side-by-side diff.", { isNew: true }),
  make("Token Table", "Dashboard", "token-table", "Design-token table.", { isNew: true }),
  make("Presence Avatars", "Dashboard", "presence", "Live collaborator avatars.", { isNew: true }),
  make("Tag Cloud", "Dashboard", "tag-cloud", "Weighted tag cloud.", { isNew: true }),
  make("Stat Bar Chart", "Dashboard", "chart", "Bar chart stat.", { variant: "bar", isNew: true }),
  make("Stat Line Chart", "Dashboard", "chart", "Line chart stat.", { variant: "line", isNew: true }),
  make("Area Chart", "Dashboard", "chart", "Area chart.", { isNew: true }),
  make("Stat Spark Tile", "Dashboard", "card", "Stat with sparkline.", { variant: "stat-spark", isNew: true }),
  make("Status Page", "Dashboard", "list", "Status row list.", { variant: "status", isNew: true }),
  make("Activity Stream", "Dashboard", "feed", "Activity feed.", { isNew: true }),
  make("Notification Center", "Dashboard", "feed", "Notification center.", { variant: "notif", isNew: true }),
  make("Dashboard Sidebar", "Dashboard", "sidebar", "App sidebar.", { isNew: true }),
  make("Kanban Pro", "Dashboard", "kanban", "Project kanban.", { isNew: true }),
  make("Stats Band Big", "Dashboard", "stats", "Big-number stats band.", { variant: "band", isNew: true }),
  make("KPI Mini Set", "Dashboard", "metric-row", "Compact KPI set.", { isNew: true }),
  make("Realtime Counter", "Dashboard", "ticker", "Animated number counter.", { isNew: true }),
  make("Health Indicator", "Dashboard", "gauge", "Health gauge.", { isNew: true }),
  make("Coverage Gauge", "Dashboard", "gauge", "Test-coverage gauge.", { isNew: true }),
  make("CPU Gauge", "Dashboard", "gauge", "CPU usage gauge.", { isNew: true }),
  make("Memory Gauge", "Dashboard", "gauge", "Memory usage gauge.", { isNew: true }),
  make("Cost Tracker", "Dashboard", "ai-token-usage", "Spend tracker.", { isNew: true }),
  make("Build Log", "Dashboard", "log-viewer", "CI/CD log stream.", { isNew: true }),

  // ---------- Marketing (25) ----------
  make("Bento Hero Grid", "Marketing", "bento-hero", "Bento-style hero.", { isNew: true }),
  make("Hero Mesh Pro", "Marketing", "hero", "Hero with mesh gradient.", { variant: "mesh", isNew: true }),
  make("Hero Terminal Pro", "Marketing", "hero", "Hero with terminal demo.", { variant: "terminal", isNew: true }),
  make("Hero Split Premium", "Marketing", "hero", "Split hero with imagery.", { variant: "split", isNew: true }),
  make("Shimmer CTA", "Marketing", "shimmer-btn", "Shimmer animated CTA.", { isNew: true }),
  make("Rainbow Shimmer CTA", "Marketing", "shimmer-btn", "Rainbow shimmer.", { variant: "rainbow", isNew: true }),
  make("Confetti Launch", "Marketing", "confetti-btn", "Confetti launch button.", { isNew: true }),
  make("Logos Marquee Pro", "Marketing", "marquee", "Auto-scrolling logo strip.", { variant: "logos", isNew: true }),
  make("Testimonial Marquee Pro", "Marketing", "testimonial", "Scrolling testimonials.", { variant: "marquee", isNew: true }),
  make("Pricing Compare Pro", "Marketing", "pricing-section", "Compare plan tiers.", { variant: "compare", isNew: true }),
  make("FAQ Section Pro", "Marketing", "faq", "FAQ with stacked answers.", { isNew: true }),
  make("Feature Bento Pro", "Marketing", "feature-section", "Bento feature grid.", { variant: "bento", isNew: true }),
  make("CTA Polarity", "Marketing", "cta", "Inverse CTA band.", { isNew: true }),
  make("Newsletter Pro", "Marketing", "newsletter", "Email capture band.", { isNew: true }),
  make("Stats Band Pro", "Marketing", "stats", "Stats band.", { variant: "band", isNew: true }),
  make("Review Card", "Marketing", "review-card", "Customer review card.", { isNew: true }),
  make("Blog Card Pro", "Marketing", "blog-card", "Article preview card.", { isNew: true }),
  make("Social Card", "Marketing", "social-card", "Tweet-style social card.", { isNew: true }),
  make("Achievement Banner", "Marketing", "achievement", "Streak / award banner.", { isNew: true }),
  make("Hero Bento Pro", "Marketing", "bento-hero", "Mixed bento hero.", { isNew: true }),
  make("Comparison Slider", "Marketing", "segment", "Compare segment.", { isNew: true }),
  make("Pricing Featured Pro", "Marketing", "card", "Featured pricing tier.", { variant: "pricing-featured", isNew: true }),
  make("Press Logos", "Marketing", "logo-strip", "Press / partner logos.", { isNew: true }),
  make("Hero Glass", "Marketing", "card", "Glass hero card.", { variant: "glass", isNew: true }),
  make("Glow CTA", "Marketing", "card", "Glowing border CTA.", { variant: "glow", isNew: true }),

  // ---------- Forms / Pickers (30) ----------
  make("Segment Control", "Forms", "segment", "iOS-style segmented control.", { isNew: true }),
  make("Emoji Picker", "Forms", "emoji-picker", "Emoji picker grid.", { isNew: true }),
  make("Country Picker", "Forms", "country-picker", "Country selector with flags.", { isNew: true }),
  make("Currency Input", "Forms", "currency-input", "Currency-aware input.", { isNew: true }),
  make("Gradient Builder", "Forms", "gradient-builder", "Gradient swatch picker.", { isNew: true }),
  make("Shortcut List", "Forms", "shortcut-list", "Keyboard shortcuts list.", { isNew: true }),
  make("Input Pro", "Forms", "input", "Premium input.", { isNew: true }),
  make("Input Icon Pro", "Forms", "input", "Input with icon.", { variant: "icon", isNew: true }),
  make("Search Pro", "Forms", "input", "Search input with kbd.", { variant: "search", isNew: true }),
  make("Password Pro", "Forms", "input", "Password with reveal.", { variant: "password", isNew: true }),
  make("Tags Input Pro", "Forms", "input", "Tag input.", { variant: "tags", isNew: true }),
  make("Mention Input Pro", "Forms", "input", "@-mention input.", { variant: "mention", isNew: true }),
  make("Textarea Pro", "Forms", "textarea", "Multi-line input.", { isNew: true }),
  make("OTP Pro", "Forms", "otp", "6-digit OTP.", { isNew: true }),
  make("PIN Pro", "Forms", "otp", "Numeric PIN input.", { variant: "pin", isNew: true }),
  make("Checkbox Pro", "Forms", "checkbox", "Checkbox group.", { variant: "group", isNew: true }),
  make("Radio Pro", "Forms", "radio", "Radio group.", { isNew: true }),
  make("Switch Pro", "Forms", "switch", "Toggle switch.", { isNew: true }),
  make("Slider Pro", "Forms", "slider", "Single-thumb slider.", { isNew: true }),
  make("Range Slider Pro", "Forms", "slider", "Two-thumb range.", { variant: "range", isNew: true }),
  make("Multi Select Pro", "Forms", "select", "Multi-select chips.", { variant: "multi", isNew: true }),
  make("Combobox Pro", "Forms", "select", "Searchable combobox.", { variant: "combobox", isNew: true }),
  make("Date Picker Pro", "Forms", "date", "Date picker.", { isNew: true }),
  make("Time Picker Pro", "Forms", "date", "Time picker.", { variant: "time", isNew: true }),
  make("Calendar Inline", "Forms", "date", "Inline calendar.", { variant: "calendar", isNew: true }),
  make("Color Picker Pro", "Forms", "color-picker", "Swatch color picker.", { isNew: true }),
  make("File Upload Pro", "Forms", "upload", "File upload.", { isNew: true }),
  make("Drag Upload Pro", "Forms", "upload", "Drag-and-drop dropzone.", { variant: "drag", isNew: true }),
  make("Rating Pro", "Forms", "rating", "Star rating.", { isNew: true }),
  make("Settings Form Pro", "Forms", "form", "Workspace settings.", { variant: "settings", isNew: true }),

  // ---------- Overlays / Navigation (20) ----------
  make("Tooltip Pro", "Overlays", "tooltip", "Hover tooltip.", { isNew: true }),
  make("Popover Pro", "Overlays", "popover", "Anchored popover.", { isNew: true }),
  make("Dropdown Pro", "Overlays", "dropdown", "Dropdown menu.", { isNew: true }),
  make("Context Menu Pro", "Overlays", "context-menu", "Right-click menu.", { isNew: true }),
  make("Menu Bar Pro", "Overlays", "menu-bar", "Top menu bar.", { isNew: true }),
  make("Modal Pro", "Overlays", "modal", "Centered modal.", { isNew: true }),
  make("Dialog Pro", "Overlays", "modal", "Form dialog.", { variant: "dialog", isNew: true }),
  make("Alert Dialog Pro", "Overlays", "modal", "Destructive confirm.", { variant: "alert", isNew: true }),
  make("Drawer Pro", "Overlays", "drawer", "Side drawer.", { isNew: true }),
  make("Sheet Pro", "Overlays", "drawer", "Bottom sheet.", { variant: "bottom", isNew: true }),
  make("Hover Card Pro", "Overlays", "hover-card", "Hover preview card.", { isNew: true }),
  make("Navbar Pro", "Navigation", "navbar", "Premium navbar.", { isNew: true }),
  make("Navbar Centered Pro", "Navigation", "navbar", "Centered navbar.", { variant: "centered", isNew: true }),
  make("Tabs Underline Pro", "Navigation", "tabs", "Underline tabs.", { isNew: true }),
  make("Tabs Pill Pro", "Navigation", "tabs", "Pill tabs.", { variant: "pill", isNew: true }),
  make("Tabs Vertical Pro", "Navigation", "tabs", "Vertical tabs.", { variant: "vertical", isNew: true }),
  make("Stepper Pro", "Navigation", "stepper", "Multi-step.", { isNew: true }),
  make("Pagination Pro", "Navigation", "pagination", "Page pagination.", { isNew: true }),
  make("Breadcrumb Pro", "Navigation", "breadcrumb", "Breadcrumb path.", { isNew: true }),
  make("Dock Pro", "Navigation", "dock", "macOS-style dock.", { isNew: true }),

  // ---------- Actions / Buttons (20) ----------
  make("Button Primary Pro", "Actions", "button", "Premium primary button.", { isNew: true }),
  make("Button Secondary Pro", "Actions", "button", "Outlined secondary.", { variant: "secondary", isNew: true }),
  make("Button Ghost Pro", "Actions", "button", "Ghost button.", { variant: "ghost", isNew: true }),
  make("Button Gradient Pro", "Actions", "button", "Gradient CTA.", { variant: "gradient", isNew: true }),
  make("Button Loading Pro", "Actions", "button", "Async pending.", { variant: "loading", isNew: true }),
  make("Button Destructive Pro", "Actions", "button", "Destructive button.", { variant: "destructive", isNew: true }),
  make("Button Sizes Pro", "Actions", "button", "Sizes scale.", { variant: "sizes", isNew: true }),
  make("Icon Button Pro", "Actions", "icon-button", "Square icon button.", { isNew: true }),
  make("Toggle Pro", "Actions", "toggle", "On/off toggle.", { isNew: true }),
  make("Button Group Pro", "Actions", "button-group", "Segmented button group.", { isNew: true }),
  make("Split Button Pro", "Actions", "split-button", "Split-action button.", { isNew: true }),
  make("FAB Pro", "Actions", "fab", "Floating action button.", { isNew: true }),
  make("Copy Button Pro", "Actions", "copy-button", "Click-to-copy.", { isNew: true }),
  make("Link Pro", "Actions", "link", "Inline link.", { isNew: true }),
  make("Shimmer Button", "Actions", "shimmer-btn", "Shimmer animated button.", { isNew: true }),
  make("Rainbow Button", "Actions", "shimmer-btn", "Rainbow shimmer.", { variant: "rainbow", isNew: true }),
  make("Launch Button", "Actions", "confetti-btn", "Launch CTA.", { isNew: true }),
  make("Theme Toggle Pro", "Actions", "theme-switcher", "Theme toggle.", { isNew: true }),
  make("Light Toggle", "Actions", "theme-switcher", "Light preview.", { variant: "light", isNew: true }),
  make("Dark Toggle", "Actions", "theme-switcher", "Dark preview.", { variant: "dark", isNew: true }),

  // ---------- Data Display (20) ----------
  make("Avatar Pro", "Data Display", "avatar", "Premium avatar.", { isNew: true }),
  make("Avatar Group Pro", "Data Display", "avatar", "Stacked avatars.", { variant: "group", isNew: true }),
  make("Avatar Status Pro", "Data Display", "avatar", "Avatar with presence.", { variant: "status", isNew: true }),
  make("Avatar Square Pro", "Data Display", "avatar", "Squircle avatar.", { variant: "square", isNew: true }),
  make("Badge Solid Pro", "Data Display", "badge", "Solid badge.", { variant: "solid", isNew: true }),
  make("Badge Outline Pro", "Data Display", "badge", "Outline badge.", { variant: "outline", isNew: true }),
  make("Badge Status Pro", "Data Display", "badge", "Status badge.", { variant: "status", isNew: true }),
  make("Badge Gradient Pro", "Data Display", "badge", "Gradient badge.", { variant: "gradient", isNew: true }),
  make("Badge Counter Pro", "Data Display", "badge", "Counter badge.", { variant: "counter", isNew: true }),
  make("Chip Pro", "Data Display", "chip", "Dismissable chip.", { isNew: true }),
  make("Tag Pro", "Data Display", "tag", "Mono caption tag.", { isNew: true }),
  make("Kbd Pro", "Data Display", "kbd", "Keyboard cap.", { isNew: true }),
  make("Table Pro", "Data Display", "table", "Hairline table.", { isNew: true }),
  make("Data Table Pro", "Data Display", "table", "Sortable data table.", { variant: "data", isNew: true }),
  make("Tree View Pro", "Data Display", "tree", "Folder tree.", { isNew: true }),
  make("Tree Files Pro", "Data Display", "tree", "Files tree.", { variant: "files", isNew: true }),
  make("Timeline Pro", "Data Display", "timeline", "Vertical timeline.", { isNew: true }),
  make("Empty State Pro", "Data Display", "empty", "Empty with action.", { isNew: true }),
  make("Description List Pro", "Data Display", "list", "Key-value list.", { variant: "desc", isNew: true }),
  make("Virtual List Pro", "Data Display", "list", "Virtualized list.", { variant: "virtual", isNew: true }),

  // ---------- Layout / Cards (10) ----------
  make("Glass Card Pro", "Layout", "card", "Glass card.", { variant: "glass", isNew: true }),
  make("Profile Card Pro", "Layout", "card", "User profile card.", { variant: "profile", isNew: true }),
  make("Product Card Pro", "Layout", "card", "Product card.", { variant: "product", isNew: true }),
  make("Stat Card Pro", "Layout", "card", "KPI stat card.", { variant: "stat", isNew: true }),
  make("Pricing Card Pro", "Layout", "card", "Pricing tier card.", { variant: "pricing", isNew: true }),
  make("Pricing Featured Card", "Layout", "card", "Featured pricing.", { variant: "pricing-featured", isNew: true }),
  make("Feature Card Pro", "Layout", "card", "Feature card.", { variant: "feature", isNew: true }),
  make("Spotlight Card Pro", "Layout", "card", "Spotlight card.", { variant: "spotlight", isNew: true }),
  make("Glow Card Pro", "Layout", "card", "Glow border card.", { variant: "glow", isNew: true }),
  make("Bento Grid Pro", "Layout", "masonry", "Bento mixed grid.", { variant: "bento", isNew: true }),
];

COMPONENTS.push(...v2);

export const CATEGORIES: Category[] = [
  "Actions",
  "Forms",
  "Navigation",
  "Overlays",
  "Data Display",
  "Feedback",
  "Layout",
  "Media",
  "Marketing",
  "AI",
  "Animation",
  "Auth",
  "Dashboard",
];

export const findComponent = (slug: string) =>
  COMPONENTS.find((c) => c.slug === slug);

export const componentsByCategory = () => {
  const map: Record<string, ComponentEntry[]> = {};
  for (const c of COMPONENTS) {
    (map[c.category] ||= []).push(c);
  }
  return map;
};

// ---------- Auto-generated extras (100+ more components) ----------
// Programmatic expansion to push the catalog beyond 500.
const extraSpecs: Array<[string, Category, string, string, string?]> = [
  ["Aurora Hero", "Marketing", "mesh-hero", "Aurora light wash hero.", "aurora"],
  ["Spotlight Hero", "Marketing", "mesh-hero", "Hero with mouse spotlight.", "spotlight"],
  ["Grid Hero", "Marketing", "mesh-hero", "Hero on a grid backdrop.", "grid"],
  ["Noise Hero", "Marketing", "mesh-hero", "Hero with film-grain noise.", "noise"],
  ["Particle Hero", "Marketing", "mesh-hero", "Hero with particle field.", "particles"],
  ["Beam CTA", "Marketing", "shimmer-cta", "CTA with animated beam.", "beam"],
  ["Glow CTA", "Marketing", "shimmer-cta", "CTA with soft glow ring.", "glow"],
  ["Gradient CTA", "Marketing", "shimmer-cta", "CTA with rotating gradient.", "rotate"],
  ["Marquee Logos", "Marketing", "logo-cloud", "Looping logo marquee.", "marquee"],
  ["Static Logos", "Marketing", "logo-cloud", "Static logo cloud.", "static"],
  ["Press Strip", "Marketing", "logo-cloud", "As featured in strip.", "press"],
  ["Feature Grid", "Marketing", "bento", "3x2 bento feature grid.", "feature"],
  ["Pricing Bento", "Marketing", "bento", "Bento pricing layout.", "pricing"],
  ["Stats Bento", "Marketing", "bento", "Bento KPI tiles.", "stats"],
  ["Stat Counter", "Data Display", "kpi", "Animated stat counter.", "counter"],
  ["Delta KPI", "Data Display", "kpi", "KPI with delta arrow.", "delta"],
  ["Sparkline KPI", "Data Display", "kpi", "KPI with sparkline.", "spark"],
  ["Gauge Radial", "Data Display", "gauge", "Radial gauge meter.", "radial"],
  ["Gauge Segment", "Data Display", "gauge", "Segmented gauge.", "segment"],
  ["Gauge Speed", "Data Display", "gauge", "Speedometer gauge.", "speed"],
  ["Line Chart", "Data Display", "chart", "Smooth line chart.", "line"],
  ["Bar Chart", "Data Display", "chart", "Bar chart with hover.", "bar"],
  ["Area Chart", "Data Display", "chart", "Filled area chart.", "area"],
  ["Donut Chart", "Data Display", "chart", "Donut with legend.", "donut"],
  ["Sankey Mini", "Data Display", "chart", "Mini sankey diagram.", "sankey"],
  ["Funnel Chart", "Data Display", "chart", "Funnel breakdown.", "funnel"],
  ["Heatmap Year", "Data Display", "heatmap", "GitHub-style heatmap.", "year"],
  ["Heatmap Hours", "Data Display", "heatmap", "Hour-of-day heatmap.", "hours"],
  ["Log Viewer", "Data Display", "logs", "Streaming log viewer."],
  ["JSON Viewer", "Data Display", "json", "Collapsible JSON tree."],
  ["Diff Viewer", "Data Display", "diff", "Unified diff viewer."],
  ["Timeline V", "Data Display", "timeline", "Vertical timeline.", "v"],
  ["Timeline H", "Data Display", "timeline", "Horizontal timeline.", "h"],
  ["Kanban Mini", "Dashboard", "kanban", "Mini kanban board."],
  ["Kanban Wide", "Dashboard", "kanban", "Wide kanban with WIP.", "wide"],
  ["Calendar Month", "Dashboard", "calendar", "Month grid calendar.", "month"],
  ["Calendar Week", "Dashboard", "calendar", "Week schedule.", "week"],
  ["Calendar Day", "Dashboard", "calendar", "Day timeline.", "day"],
  ["Sidebar Nav", "Navigation", "sidebar", "Collapsible sidebar."],
  ["Sidebar Icons", "Navigation", "sidebar", "Icon-only rail.", "icons"],
  ["Sidebar Sections", "Navigation", "sidebar", "Grouped sidebar.", "sections"],
  ["Top Tabs", "Navigation", "tabs", "Top page tabs.", "top"],
  ["Pill Tabs", "Navigation", "tabs", "Pill segmented tabs.", "pill"],
  ["Underline Tabs", "Navigation", "tabs", "Underline tabs.", "underline"],
  ["Vertical Tabs", "Navigation", "tabs", "Vertical tab rail.", "vertical"],
  ["Stepper Linear", "Navigation", "stepper", "Linear stepper."],
  ["Stepper Vertical", "Navigation", "stepper", "Vertical stepper.", "vertical"],
  ["Stepper Numbered", "Navigation", "stepper", "Numbered stepper.", "number"],
  ["Breadcrumb Slash", "Navigation", "breadcrumb", "Slash breadcrumb.", "slash"],
  ["Breadcrumb Chevron", "Navigation", "breadcrumb", "Chevron breadcrumb.", "chev"],
  ["Pagination Bar", "Navigation", "pagination", "Numbered pager."],
  ["Pagination Compact", "Navigation", "pagination", "Compact prev/next.", "compact"],
  ["Pagination Cursor", "Navigation", "pagination", "Cursor pager.", "cursor"],
  ["Sign In Form", "Auth", "auth", "Sign-in card.", "signin"],
  ["Sign Up Form", "Auth", "auth", "Sign-up card.", "signup"],
  ["Magic Link", "Auth", "auth", "Magic link request.", "magic"],
  ["OTP Form", "Auth", "auth", "One-time password form.", "otp"],
  ["Forgot Password", "Auth", "auth", "Forgot password.", "forgot"],
  ["Social Logins", "Auth", "auth", "OAuth provider buttons.", "social"],
  ["Org Switcher", "Auth", "auth", "Organization switcher.", "org"],
  ["AI Chat Bubble", "AI", "ai-chat", "Single chat bubble.", "bubble"],
  ["AI Chat Thread", "AI", "ai-chat", "Threaded chat.", "thread"],
  ["AI Reasoning", "AI", "ai-chat", "Streaming reasoning panel.", "reason"],
  ["AI Tool Call", "AI", "ai-chat", "Tool-call card.", "tool"],
  ["AI Token Meter", "AI", "ai-chat", "Token usage meter.", "tokens"],
  ["AI Persona", "AI", "ai-chat", "AI persona switcher.", "persona"],
  ["AI Profile Card", "AI", "ai-chat", "AI agent profile.", "profile"],
  ["AI Status", "AI", "ai-chat", "Agent status dot.", "status"],
  ["AI Prompt Box", "AI", "ai-chat", "Composer with attachments.", "composer"],
  ["AI Suggestions", "AI", "ai-chat", "Prompt suggestions.", "suggest"],
  ["Toast Success", "Feedback", "toast", "Success toast.", "success"],
  ["Toast Error", "Feedback", "toast", "Error toast.", "error"],
  ["Toast Loading", "Feedback", "toast", "Loading toast.", "loading"],
  ["Toast Action", "Feedback", "toast", "Toast with action.", "action"],
  ["Banner Info", "Feedback", "banner", "Info banner.", "info"],
  ["Banner Warn", "Feedback", "banner", "Warning banner.", "warn"],
  ["Banner Promo", "Feedback", "banner", "Promo banner.", "promo"],
  ["Empty Inbox", "Feedback", "empty", "Empty inbox state.", "inbox"],
  ["Empty Search", "Feedback", "empty", "Empty search.", "search"],
  ["Empty Files", "Feedback", "empty", "Empty files.", "files"],
  ["Skeleton Card", "Feedback", "skeleton", "Card skeleton.", "card"],
  ["Skeleton Table", "Feedback", "skeleton", "Table skeleton.", "table"],
  ["Skeleton Article", "Feedback", "skeleton", "Article skeleton.", "article"],
  ["Spinner Dots", "Feedback", "spinner", "Three-dot spinner.", "dots"],
  ["Spinner Ring", "Feedback", "spinner", "Ring spinner.", "ring"],
  ["Spinner Bars", "Feedback", "spinner", "Bar spinner.", "bars"],
  ["Progress Bar", "Feedback", "progress", "Linear progress.", "bar"],
  ["Progress Steps", "Feedback", "progress", "Stepped progress.", "steps"],
  ["Progress Radial", "Feedback", "progress", "Radial progress.", "radial"],
  ["File Drop", "Forms", "file", "Dropzone uploader.", "drop"],
  ["File List", "Forms", "file", "Upload list.", "list"],
  ["File Preview", "Forms", "file", "Image preview tile.", "preview"],
  ["Slider Range", "Forms", "slider", "Range slider.", "range"],
  ["Slider Stepped", "Forms", "slider", "Stepped slider.", "stepped"],
  ["Slider Color", "Forms", "slider", "Color hue slider.", "color"],
  ["Color Picker", "Forms", "color", "HSL color picker."],
  ["Date Picker", "Forms", "date", "Single date picker."],
  ["Date Range", "Forms", "date", "Date range picker.", "range"],
  ["Time Picker", "Forms", "date", "Time picker.", "time"],
  ["Combobox", "Forms", "combobox", "Searchable combobox."],
  ["Multi Combobox", "Forms", "combobox", "Multi-select combobox.", "multi"],
  ["Tag Input", "Forms", "tag-input", "Chip-based tag input."],
  ["Mention Input", "Forms", "tag-input", "@mention input.", "mention"],
  ["OTP Input", "Forms", "otp", "Six-slot OTP input."],
  ["Phone Input", "Forms", "phone", "International phone input."],
  ["Card Input", "Forms", "card-input", "Credit card input."],
  ["Address Form", "Forms", "address", "Address form."],
  ["Survey Slider", "Forms", "slider", "Likert-style survey.", "survey"],
  ["Rating Stars", "Forms", "rating", "Star rating."],
  ["Rating Hearts", "Forms", "rating", "Heart rating.", "heart"],
  ["Rating Emoji", "Forms", "rating", "Emoji rating.", "emoji"],
  ["Switch Inline", "Forms", "switch", "Inline label switch.", "inline"],
  ["Switch Card", "Forms", "switch", "Card-style switch.", "card"],
  ["Checkbox Card", "Forms", "checkbox", "Card checkbox.", "card"],
  ["Radio Card", "Forms", "radio", "Card radio group.", "card"],
  ["Segmented Picker", "Forms", "segmented", "Segmented picker."],
  ["Code Block", "Data Display", "code", "Syntax code block."],
  ["Code Diff", "Data Display", "code", "Side-by-side diff.", "diff"],
  ["Terminal Stream", "Data Display", "terminal", "Streaming terminal.", "stream"],
  ["Terminal Prompt", "Data Display", "terminal", "Prompt terminal.", "prompt"],
  ["Quote Card", "Marketing", "quote", "Quote testimonial card."],
  ["Quote Marquee", "Marketing", "quote", "Marquee quotes.", "marquee"],
  ["Quote Grid", "Marketing", "quote", "Quote grid.", "grid"],
  ["Pricing Card", "Marketing", "pricing", "Single pricing card."],
  ["Pricing Trio", "Marketing", "pricing", "Three-tier pricing.", "trio"],
  ["Pricing Toggle", "Marketing", "pricing", "Monthly/yearly toggle.", "toggle"],
  ["FAQ Accordion", "Marketing", "faq", "Accordion FAQ."],
  ["FAQ Grid", "Marketing", "faq", "Grid FAQ.", "grid"],
  ["Newsletter Inline", "Marketing", "newsletter", "Inline newsletter."],
  ["Newsletter Card", "Marketing", "newsletter", "Card newsletter.", "card"],
  ["3D Tilt Card", "Animation", "tilt", "Pointer-tilt card."],
  ["Magnetic Button", "Animation", "magnetic", "Magnetic cursor button."],
  ["Scramble Text", "Animation", "scramble", "Text scramble effect."],
  ["Marquee Row", "Animation", "marquee", "Infinite marquee row."],
  ["Marquee Vertical", "Animation", "marquee", "Vertical marquee.", "vertical"],
  ["Reveal On Scroll", "Animation", "reveal", "Scroll-reveal section."],
  ["Stagger List", "Animation", "stagger", "Stagger entrance list."],
  ["Spring Counter", "Animation", "counter", "Spring number counter."],
];

for (const [name, cat, kind, desc, variant] of extraSpecs) {
  if (!COMPONENTS.find((c) => c.slug === slugify(name))) {
    COMPONENTS.push(make(name, cat, kind, desc, { variant, isNew: true }));
  }
}


export const totalCount = COMPONENTS.length;