/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsSlugRouteImport } from './routes/components.$slug'
import { Route as ComponentsCategoryCategoryRouteImport } from './routes/components.category.$category'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCategoryCategoryRoute =
  ComponentsCategoryCategoryRouteImport.update({
    id: '/category/$category',
    path: '/category/$category',
    getParentRoute: () => ComponentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/docs': typeof DocsRoute
  '/showcase': typeof ShowcaseRoute
  '/templates': typeof TemplatesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/category/$category': typeof ComponentsCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/docs': typeof DocsRoute
  '/showcase': typeof ShowcaseRoute
  '/templates': typeof TemplatesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/category/$category': typeof ComponentsCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/docs': typeof DocsRoute
  '/showcase': typeof ShowcaseRoute
  '/templates': typeof TemplatesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/category/$category': typeof ComponentsCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/docs'
    | '/showcase'
    | '/templates'
    | '/components/$slug'
    | '/components/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/docs'
    | '/showcase'
    | '/templates'
    | '/components/$slug'
    | '/components/category/$category'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/docs'
    | '/showcase'
    | '/templates'
    | '/components/$slug'
    | '/components/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  DocsRoute: typeof DocsRoute
  ShowcaseRoute: typeof ShowcaseRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/category/$category': {
      id: '/components/category/$category'
      path: '/category/$category'
      fullPath: '/components/category/$category'
      preLoaderRoute: typeof ComponentsCategoryCategoryRouteImport
      parentRoute: typeof ComponentsRoute
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsCategoryCategoryRoute: typeof ComponentsCategoryCategoryRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsCategoryCategoryRoute: ComponentsCategoryCategoryRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  DocsRoute: DocsRoute,
  ShowcaseRoute: ShowcaseRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
